name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'Breaking Changes'
    label: 'breaking-changes'
  - title: 'Features'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Dependencies'
    label: 'dependencies' #dependabot
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'breaking-changes'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'dependencies'
  default: patch
template: |
  ## Changes

  $CHANGES
